// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/styles.css.ts";
import * as $$0 from "./islands/Carousel/index.tsx";
import * as $$1 from "./islands/ShowCaseCarousel/index.tsx";
import * as $$2 from "./islands/SliderJS/index.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/styles.css.ts": $1,
  },
  islands: {
    "./islands/Carousel/index.tsx": $$0,
    "./islands/ShowCaseCarousel/index.tsx": $$1,
    "./islands/SliderJS/index.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
